CREATE TABLE IF NOT EXISTS players (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
position VARCHAR(50) NOT NULL,
matches INT DEFAULT 0,
goals INT DEFAULT 0,
assists INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS champions_league (
id INT AUTO_INCREMENT PRIMARY KEY,
season YEAR NOT NULL,
winner VARCHAR(100) NOT NULL,
mvp VARCHAR(100) NOT NULL,
top_scorer VARCHAR(100) NOT NULL,
goals INT DEFAULT 0
);