name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Version should be fine

      - name: Cache Docker layers
        uses: actions/cache@v3  # Updated to the latest version
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.yml run --rm backend pytest

      - name: Push Docker images to DockerHub (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Deploy to Production (optional)
        run: |
          # Here, you can add your deployment steps, for example:
          # ssh user@your-server 'docker pull my-image && docker-compose up -d'
